// Package service wires the daemon into the platform service manager:
// it generates a systemd user unit (Linux) or a launchd agent (macOS)
// with the resolved binary and config paths baked in — npm installs hide
// the binary deep inside node_modules, so hand-written unit files with
// guessed paths do not work; generating them from os.Executable does.
// Lifecycle is delegated to the service manager (supervision, restart,
// boot autostart, logs) rather than reimplemented in-process.
package service

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// ErrUnsupported is returned on platforms without service support.
var ErrUnsupported = errors.New("service management is supported on Linux (systemd user units) and macOS (launchd) only")

// ServiceName is the service identity in systemd; LaunchdLabel mirrors
// deploy/launchd/com.synapse.proxy.plist so existing setups coexist.
const (
	ServiceName  = "synapse"
	LaunchdLabel = "com.synapse.proxy"
)

// Paths are the locations baked into the generated unit file.
type Paths struct {
	Binary string // resolved real path of this executable
	Config string // default config path
	Unit   string // unit/plist file to generate
	Log    string // stdout/stderr sink ("" = journald on Linux)
}

// DetectPaths resolves the platform-standard paths for the current user.
// goos is a parameter so tests can exercise every platform.
func DetectPaths(goos string) (Paths, error) {
	exe, err := os.Executable()
	if err != nil {
		return Paths{}, fmt.Errorf("resolve executable: %w", err)
	}
	binary, err := filepath.EvalSymlinks(exe)
	if err != nil {
		return Paths{}, fmt.Errorf("resolve symlinks for %s: %w", exe, err)
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return Paths{}, fmt.Errorf("resolve home dir: %w", err)
	}
	config := filepath.Join(home, ".config", "synapse", "config.yaml")
	switch goos {
	case "linux":
		// os.UserConfigDir is XDG_CONFIG_HOME or ~/.config.
		if dir, err := os.UserConfigDir(); err == nil {
			config = filepath.Join(dir, "synapse", "config.yaml")
		}
		return Paths{
			Binary: binary,
			Config: config,
			Unit:   filepath.Join(home, ".config", "systemd", "user", ServiceName+".service"),
		}, nil
	case "darwin":
		return Paths{
			Binary: binary,
			Config: config,
			Unit:   filepath.Join(home, "Library", "LaunchAgents", LaunchdLabel+".plist"),
			Log:    filepath.Join(home, "Library", "Logs", "synapse.log"),
		}, nil
	default:
		return Paths{}, ErrUnsupported
	}
}

// UnitText renders the systemd user unit for the given paths.
func UnitText(p Paths) string {
	return fmt.Sprintf(`# synapse systemd user unit — generated by `+"`synapse service install`"+`.
# Edit ~/.config/synapse/config.yaml, then `+"`systemctl --user restart synapse`"+`.
[Unit]
Description=synapse protocol adapter (Responses API -> Chat Completions)
Documentation=https://github.com/dncore/synapse-protocol-adapter
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s --config %s
# Graceful shutdown: SIGTERM drains in-flight streams up to shutdown.timeout;
# TimeoutStopSec must exceed it.
KillSignal=SIGTERM
TimeoutStopSec=35s
Restart=on-failure
RestartSec=2s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
`, p.Binary, p.Config)
}

// PlistText renders the launchd agent plist for the given paths.
func PlistText(p Paths) string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!-- synapse launchd agent — generated by `+"`synapse service install`"+`. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>%s</string>

    <key>ProgramArguments</key>
    <array>
        <string>%s</string>
        <string>--config</string>
        <string>%s</string>
    </array>

    <!-- Start at login; restart if the process exits or crashes.
         SIGTERM drains in-flight streams (graceful shutdown). -->
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ProcessType</key>
    <string>Background</string>

    <key>StandardOutPath</key>
    <string>%s</string>
    <key>StandardErrorPath</key>
    <string>%s</string>
</dict>
</plist>
`, LaunchdLabel, p.Binary, p.Config, p.Log, p.Log)
}

// run executes a service-manager command, surfacing its combined output
// on failure.
func run(name string, args ...string) error {
	out, err := exec.Command(name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %s", name, strings.Join(args, " "), strings.TrimSpace(string(out)))
	}
	return nil
}

// runOk reports whether a command exits zero (used for state probes).
func runOk(name string, args ...string) bool {
	return exec.Command(name, args...).Run() == nil
}

// Install generates the unit file, enables boot autostart, and (with
// startNow) starts the service. configPath overrides the default config
// location baked into the unit.
func Install(configPath string, startNow bool) error {
	p, err := DetectPaths(runtime.GOOS)
	if err != nil {
		return err
	}
	if configPath != "" {
		p.Config = configPath
	}
	if _, err := os.Stat(p.Config); err != nil {
		return fmt.Errorf("config %s not found — run `synapse init` first: %w", p.Config, err)
	}
	if _, err := os.Stat(p.Unit); err == nil {
		return fmt.Errorf("%s already exists — `synapse service uninstall` first", p.Unit)
	}
	if err := os.MkdirAll(filepath.Dir(p.Unit), 0o755); err != nil {
		return err
	}
	switch runtime.GOOS {
	case "linux":
		err = os.WriteFile(p.Unit, []byte(UnitText(p)), 0o644)
	case "darwin":
		err = os.WriteFile(p.Unit, []byte(PlistText(p)), 0o644)
	}
	if err != nil {
		return err
	}

	if runtime.GOOS == "linux" {
		if err := run("systemctl", "--user", "daemon-reload"); err != nil {
			return err
		}
		if err := run("systemctl", "--user", "enable", ServiceName); err != nil {
			return err
		}
		// Linger keeps the user manager alive after logout so the
		// service survives reconnects/headless use.
		run("loginctl", "enable-linger") // best-effort; non-fatal
		if startNow {
			return run("systemctl", "--user", "start", ServiceName)
		}
		fmt.Printf("service installed: %s\nautostart enabled; start it with `synapse start`\n", p.Unit)
		return nil
	}

	// darwin: bootstrap loads and (RunAtLoad) starts the agent.
	if err := run("launchctl", "bootstrap", guiDomain(), p.Unit); err != nil {
		return err
	}
	if !startNow {
		fmt.Printf("service installed: %s (starts at login)\n", p.Unit)
	}
	return nil
}

// Uninstall stops the service, disables autostart, and removes the unit
// file. Config and logs are kept.
func Uninstall() error {
	p, err := DetectPaths(runtime.GOOS)
	if err != nil {
		return err
	}
	if _, err := os.Stat(p.Unit); err != nil {
		return fmt.Errorf("no service installed at %s", p.Unit)
	}
	if runtime.GOOS == "linux" {
		// disable --now tolerates an inactive unit; a not-yet-loaded
		// unit still exits 0 for the disable part.
		if err := run("systemctl", "--user", "disable", "--now", ServiceName); err != nil {
			return err
		}
		run("loginctl", "disable-linger") // best-effort
	} else {
		run("launchctl", "bootout", guiDomain()+"/"+LaunchdLabel) // stop+unload; absent is fine
	}
	if err := os.Remove(p.Unit); err != nil {
		return err
	}
	if runtime.GOOS == "linux" {
		return run("systemctl", "--user", "daemon-reload")
	}
	fmt.Printf("service removed (config kept at %s)\n", p.Config)
	return nil
}

// Start, Stop, and Restart delegate to the service manager so in-flight
// streams get the same graceful drain as a bare-process Ctrl-C.
func Start() error {
	if runtime.GOOS == "darwin" {
		if runOk("launchctl", "print", guiDomain()+"/"+LaunchdLabel) {
			return run("launchctl", "kickstart", guiDomain()+"/"+LaunchdLabel)
		}
		p, err := DetectPaths(runtime.GOOS)
		if err != nil {
			return err
		}
		return run("launchctl", "bootstrap", guiDomain(), p.Unit)
	}
	return run("systemctl", "--user", "start", ServiceName)
}

func Stop() error {
	if runtime.GOOS == "darwin" {
		return run("launchctl", "bootout", guiDomain()+"/"+LaunchdLabel)
	}
	return run("systemctl", "--user", "stop", ServiceName)
}

func Restart() error {
	if runtime.GOOS == "darwin" {
		return run("launchctl", "kickstart", "-k", guiDomain()+"/"+LaunchdLabel)
	}
	return run("systemctl", "--user", "restart", ServiceName)
}

func guiDomain() string {
	return fmt.Sprintf("gui/%d", os.Getuid())
}
